services:    
  ordinarias:
    build: .
    environment:
      - TSE_API=ordinarias
    <<: &default
      image: tse_cand_contas
      volumes:
        - D:\Proj\TSE - Candidaturas\Kubernates\desafio-airton:/app
        #- tse-jsons:/app
      command: ["python", "main.py"]

  municipios:
    <<: *default
    environment:
      - TSE_API=municipios
    depends_on:
      - ordinarias

  candidatos:
    <<: *default
    environment:
      - TSE_API=candidatos
    depends_on:
      - municipios

  candidato:
    <<: *default
    environment:
      - TSE_API=candidato
    depends_on:
      - candidatos


# volumes:
#   tse-jsons:
